# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b760beb3d36110798d84264f8f557ca8dc4a2ee29c08e6cffac2652dec3641a59e8f51020749a26edeaea8b4c19e02b05e4c2864d79aba44832ddcbe4ee95f9

test:
  secret_key_base: 23c24dd8e889c94cea6a4c01ca180d2fb0093a56ae491a1f7cdddedf5c9da4f02f23ba3fcd29755ea3e3abd3246e3f64d383fc8390d6db4fcdc7080d81834983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
